[global]
excludes = [
    "*.lock",
    "*.patch",
    "package-lock.json",
    "go.mod",
    "go.sum",
    ".gitmodules",
    ".hgignore",
    ".svnignore",
    "lefthook.yml",
]
on-unmatched = "warn"

[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]

[formatter.biome]
command = "biome"
includes = [
    "*.js",
    "*.mjs",
    "*.cjs",
    "*.ts",
    "*.mts",
    "*.cts",
    "*.d.ts",
    "*.d.mts",
    "*.d.cts",
    "*.jsx",
    "*.tsx",
    "*.json",
    "*.jsonc",
    "*.css",
    "*.graphql",
    "*.gql",
    "*.html",
]
options = ["format", "--write"]

[formatter.prettier]
command = "prettier"
includes = [
    "*.md",
    "*.mdx",
    "*.yaml",
    "*.yml",
]
options = ["--write"]

[formatter.shfmt]
command = "shfmt"
includes = ["*.sh", "*.bash", "*.envrc", "*.envrc.*"]
options = ["-s", "-w", "-i", "2"]

[formatter.actionlint]
command = "actionlint"
includes = [
    ".github/workflows/*.yml",
    ".github/workflows/*.yaml",
]
